## Install yfinance

In [1]:
!pip install yfinance

Looking in indexes: https://pypi.org/simple, https://packagecloud.io/github/git-lfs/pypi/simple
Requirement already satisfied: yfinance in /home/leosmigel/Development/environments/venv/lib/python3.10/site-packages (0.1.68)
Requirement already satisfied: lxml>=4.5.1 in /home/leosmigel/Development/environments/venv/lib/python3.10/site-packages (from yfinance) (4.7.1)
Requirement already satisfied: multitasking>=0.0.7 in /home/leosmigel/Development/environments/venv/lib/python3.10/site-packages (from yfinance) (0.0.10)
Requirement already satisfied: numpy>=1.15 in /home/leosmigel/Development/environments/venv/lib/python3.10/site-packages (from yfinance) (1.21.4)
Requirement already satisfied: requests>=2.26 in /home/leosmigel/Development/environments/venv/lib/python3.10/site-packages (from yfinance) (2.26.0)
Requirement already satisfied: pandas>=0.24 in /home/leosmigel/Development/environments/venv/lib/python3.10/site-packages (from yfinance) (1.3.5)
Requirement already satisfied: python-dateutil>=2.7.3 in /home/leosmigel/Development/environments/venv/lib/python3.10/site-packages (from pandas>=0.24->yfinance) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /home/leosmigel/Development/environments/venv/lib/python3.10/site-packages (from pandas>=0.24->yfinance) (2021.3)
Requirement already satisfied: charset-normalizer~=2.0.0 in /home/leosmigel/Development/environments/venv/lib/python3.10/site-packages (from requests>=2.26->yfinance) (2.0.9)
Requirement already satisfied: certifi>=2017.4.17 in /home/leosmigel/Development/environments/venv/lib/python3.10/site-packages (from requests>=2.26->yfinance) (2021.10.8)
Requirement already satisfied: idna<4,>=2.5 in /home/leosmigel/Development/environments/venv/lib/python3.10/site-packages (from requests>=2.26->yfinance) (3.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/leosmigel/Development/environments/venv/lib/python3.10/site-packages (from requests>=2.26->yfinance) (1.26.7)
Requirement already satisfied: six>=1.5 in /home/leosmigel/Development/environments/venv/lib/python3.10/site-packages (from python-dateutil>=2.7.3->pandas>=0.24->yfinance) (1.16.0)

## Import yfinance and Pandas

In [2]:
import pandas as pd
import yfinance as yf

In [3]:
dir(yf)

['Ticker',
 'Tickers',
 '__all__',
 '__author__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 'base',
 'download',
 'multi',
 'pdr_override',
 'shared',
 'ticker',
 'tickers',
 'utils',
 'version']

## How to Download Historical Price Data Using yfinance

We can download data for one ticker using the Ticker object and multiple tickers using the download method.

### Download One Ticker Using yfinance

First, we need to create a ticker object and then use that object to get our data. Creating a ticker object is straightforward:

In [6]:
obj = yf.Ticker('goog')
obj

yfinance.Ticker object <GOOG>

In [7]:
dir(obj)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_analysis',
 '_balancesheet',
 '_base_url',
 '_calendar',
 '_cashflow',
 '_download_options',
 '_earnings',
 '_expirations',
 '_financials',
 '_fundamentals',
 '_get_fundamentals',
 '_history',
 '_info',
 '_institutional_holders',
 '_isin',
 '_major_holders',
 '_mutualfund_holders',
 '_news',
 '_options2df',
 '_recommendations',
 '_scrape_url',
 '_shares',
 '_sustainability',
 'actions',
 'analysis',
 'balance_sheet',
 'balancesheet',
 'calendar',
 'cashflow',
 'dividends',
 'earnings',
 'financials',
 'get_actions',
 'get_analysis',
 'get_balance_sheet',
 'get_balancesheet',
 'get_calendar',
 'get_cashflow',
 'get_dividends',
 'get_earnings',
 'get_financials',
 'get_info',
 'get_institutional_holders',
 'get_isin',
 'get_major_holders',
 'get_mutualfund_holders',
 'get_news',
 'get_recommendations',
 'get_shares',
 'get_splits',
 'get_sustainability',
 'history',
 'info',
 'institutional_holders',
 'isin',
 'major_holders',
 'mutualfund_holders',
 'news',
 'option_chain',
 'options',
 'quarterly_balance_sheet',
 'quarterly_balancesheet',
 'quarterly_cashflow',
 'quarterly_earnings',
 'quarterly_financials',
 'recommendations',
 'session',
 'shares',
 'splits',
 'stats',
 'sustainability',
 'ticker']

In [8]:
goog = yf.Ticker('goog')
data = goog.history()
data.head()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2021-12-13,2968.879883,2971.250000,2927.199951,2934.090088,1205200,0,0
2021-12-14,2895.399902,2908.840088,2844.850098,2899.409912,1238900,0,0
2021-12-15,2887.320068,2950.344971,2854.110107,2947.370117,1364000,0,0
2021-12-16,2961.540039,2971.030029,2881.850098,2896.770020,1370000,0,0
2021-12-17,2854.290039,2889.201904,2835.760010,2856.060059,2162800,0,0

In [9]:
data = goog.history(interval='1m', start='2022-01-03', end='2022-01-10')
data.head()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Datetime,,,,,,,
2022-01-03 09:30:00-05:00,2889.510010,2901.020020,2887.733398,2899.060059,67320,0,0
2022-01-03 09:31:00-05:00,2900.520020,2906.060059,2900.489990,2904.580078,8142,0,0
2022-01-03 09:32:00-05:00,2904.719971,2904.719971,2896.310059,2899.209961,7069,0,0
2022-01-03 09:33:00-05:00,2898.699951,2898.699951,2898.699951,2898.699951,623,0,0
2022-01-03 09:34:00-05:00,2896.209961,2896.330078,2894.913086,2896.239990,3443,0,0

### Download Multiple Tickers Using yfinance

In [10]:
data = yf.download(['GOOG','META'], period='1mo')
data.head()

[*********************100%***********************]  2 of 2 completed

              Adj Close               Close                High         \
                   GOOG   META         GOOG   META         GOOG   META
Date
2021-12-13  2934.090088  15.24  2934.090088  15.24  2971.250000  15.55
2021-12-14  2899.409912  15.06  2899.409912  15.06  2908.840088  15.17
2021-12-15  2947.370117  15.28  2947.370117  15.28  2950.344971  15.28
2021-12-16  2896.770020  14.79  2896.770020  14.79  2971.030029  15.46
2021-12-17  2856.060059  14.90  2856.060059  14.90  2889.201904  15.01

                    Low                 Open          Volume
                   GOOG    META         GOOG   META     GOOG     META
Date
2021-12-13  2927.199951  15.130  2968.879883  15.53  1205200  2178500
2021-12-14  2844.850098  14.850  2895.399902  15.02  1238900  2662900
2021-12-15  2854.110107  14.615  2887.320068  14.95  1364000  2356300
2021-12-16  2881.850098  14.680  2961.540039  15.45  1370000  2511100
2021-12-17  2835.760010  14.525  2854.290039  14.58  2162800  2281500

In [11]:
data = yf.download(['GOOG','META'], start='2021-12-10', end='2021-12-30', group_by='ticker')
data.head()

[*********************100%***********************]  2 of 2 completed

             META                                                  GOOG  \
             Open   High     Low  Close Adj Close   Volume         Open
Date
2021-12-10  15.77  15.83  15.390  15.52     15.52  1845200  2982.000000
2021-12-13  15.53  15.55  15.130  15.24     15.24  2178500  2968.879883
2021-12-14  15.02  15.17  14.850  15.06     15.06  2662900  2895.399902
2021-12-15  14.95  15.28  14.615  15.28     15.28  2356300  2887.320068
2021-12-16  15.45  15.46  14.680  14.79     14.79  2511100  2961.540039


                   High          Low        Close    Adj Close   Volume
Date
2021-12-10  2988.000000  2947.149902  2973.500000  2973.500000  1081700
2021-12-13  2971.250000  2927.199951  2934.090088  2934.090088  1205200
2021-12-14  2908.840088  2844.850098  2899.409912  2899.409912  1238900
2021-12-15  2950.344971  2854.110107  2947.370117  2947.370117  1364000
2021-12-16  2971.030029  2881.850098  2896.770020  2896.770020  1370000

## How to Download Fundamental Data Using yfinance

We can loop through multiple tickers objects to download fundamental data for various tickers.

In [14]:
dhr = yf.Ticker('DHR')
info = dhr.info
info.keys()

dict_keys(['zip', 'sector', 'fullTimeEmployees', 'longBusinessSummary', 'city', 'phone', 'state', 'country', 'companyOfficers', 'website', 'maxAge', 'address1', 'fax', 'industry', 'address2', 'ebitdaMargins', 'profitMargins', 'grossMargins', 'operatingCashflow', 'revenueGrowth', 'operatingMargins', 'ebitda', 'targetLowPrice', 'recommendationKey', 'grossProfits', 'freeCashflow', 'targetMedianPrice', 'currentPrice', 'earningsGrowth', 'currentRatio', 'returnOnAssets', 'numberOfAnalystOpinions', 'targetMeanPrice', 'debtToEquity', 'returnOnEquity', 'targetHighPrice', 'totalCash', 'totalDebt', 'totalRevenue', 'totalCashPerShare', 'financialCurrency', 'revenuePerShare', 'quickRatio', 'recommendationMean', 'exchange', 'shortName', 'longName', 'exchangeTimezoneName', 'exchangeTimezoneShortName', 'isEsgPopulated', 'gmtOffSetMilliseconds', 'quoteType', 'symbol', 'messageBoardId', 'market', 'annualHoldingsTurnover', 'enterpriseToRevenue', 'beta3Year', 'enterpriseToEbitda', '52WeekChange', 'morningStarRiskRating', 'forwardEps', 'revenueQuarterlyGrowth', 'sharesOutstanding', 'fundInceptionDate', 'annualReportExpenseRatio', 'totalAssets', 'bookValue', 'sharesShort', 'sharesPercentSharesOut', 'fundFamily', 'lastFiscalYearEnd', 'heldPercentInstitutions', 'netIncomeToCommon', 'trailingEps', 'lastDividendValue', 'SandP52WeekChange', 'priceToBook', 'heldPercentInsiders', 'nextFiscalYearEnd', 'yield', 'mostRecentQuarter', 'shortRatio', 'sharesShortPreviousMonthDate', 'floatShares', 'beta', 'enterpriseValue', 'priceHint', 'threeYearAverageReturn', 'lastSplitDate', 'lastSplitFactor', 'legalType', 'lastDividendDate', 'morningStarOverallRating', 'earningsQuarterlyGrowth', 'priceToSalesTrailing12Months', 'dateShortInterest', 'pegRatio', 'ytdReturn', 'forwardPE', 'lastCapGain', 'shortPercentOfFloat', 'sharesShortPriorMonth', 'impliedSharesOutstanding', 'category', 'fiveYearAverageReturn', 'previousClose', 'regularMarketOpen', 'twoHundredDayAverage', 'trailingAnnualDividendYield', 'payoutRatio', 'volume24Hr', 'regularMarketDayHigh', 'navPrice', 'averageDailyVolume10Day', 'regularMarketPreviousClose', 'fiftyDayAverage', 'trailingAnnualDividendRate', 'open', 'toCurrency', 'averageVolume10days', 'expireDate', 'algorithm', 'dividendRate', 'exDividendDate', 'circulatingSupply', 'startDate', 'regularMarketDayLow', 'currency', 'trailingPE', 'regularMarketVolume', 'lastMarket', 'maxSupply', 'openInterest', 'marketCap', 'volumeAllCurrencies', 'strikePrice', 'averageVolume', 'dayLow', 'ask', 'askSize', 'volume', 'fiftyTwoWeekHigh', 'fromCurrency', 'fiveYearAvgDividendYield', 'fiftyTwoWeekLow', 'bid', 'tradeable', 'dividendYield', 'bidSize', 'dayHigh', 'regularMarketPrice', 'preMarketPrice', 'logo_url', 'trailingPegRatio'])

In [15]:
info['sector']

'Healthcare'

In [18]:
dhr.earnings

          Revenue    Earnings
Year
2017  15518800000  2492100000
2018  17049000000  2651000000
2019  17911000000  3008000000
2020  22284000000  3646000000

In [19]:
dhr.get_financials()

,2020-12-31,2019-12-31,2018-12-31,2017-12-31
Research Development,1348000000.0,1126000000.0,1059000000.0,956400000.0
Effect Of Accounting Charges,None,None,None,None
Income Before Tax,4495000000.0,3305000000.0,2962000000.0,2543200000.0
Minority Interest,11000000.0,11000000.0,12300000.0,9600000.0
Net Income,3646000000.0,3008000000.0,2651000000.0,2492100000.0
Selling General Administrative,6880000000.0,5577000000.0,5356000000.0,5011900000.0
Gross Profit,12932000000.0,9984000000.0,9505000000.0,8571300000.0
Ebit,4704000000.0,3281000000.0,3090000000.0,2603000000.0
Operating Income,4704000000.0,3281000000.0,3090000000.0,2603000000.0
Other Operating Expenses,None,None,None,None
Interest Expense,-275000000.0,-108000000.0,-137000000.0,-140100000.0
Extraordinary Items,None,None,None,None
Non Recurring,None,None,None,None
Other Items,None,None,None,None
Income Tax Expense,849000000.0,873000000.0,556000000.0,371000000.0
Total Revenue,22284000000.0,17911000000.0,17049000000.0,15518800000.0
Total Operating Expenses,17580000000.0,14630000000.0,13959000000.0,12915800000.0
Cost Of Revenue,9352000000.0,7927000000.0,7544000000.0,6947500000.0
Total Other Income Expense Net,-209000000.0,24000000.0,-128000000.0,-59800000.0
Discontinued Operations,NaN,576000000.0,245000000.0,319900000.0
Net Income From Continuing Ops,3646000000.0,2432000000.0,2406000000.0,2172200000.0
Net Income Applicable To Common Shares,3510000000.0,2940000000.0,2651000000.0,2492100000.0

In [20]:
pnl = dhr.financials
bs = dhr.balancesheet
cf = dhr.cashflow
fs = pd.concat([pnl,bs,cf])
fs

,2020-12-31,2019-12-31,2018-12-31,2017-12-31
Research Development,1348000000.0,1126000000.0,1059000000.0,956400000.0
Effect Of Accounting Charges,None,None,None,None
Income Before Tax,4495000000.0,3305000000.0,2962000000.0,2543200000.0
Minority Interest,11000000.0,11000000.0,12300000.0,9600000.0
Net Income,3646000000.0,3008000000.0,2651000000.0,2492100000.0
...,...,...,...,...
Change To Inventory,-123000000.0,-22000000.0,-134000000.0,3100000.0
Change To Account Receivables,-264000000.0,-157000000.0,-55000000.0,-142500000.0
Other Cashflows From Financing Activities,-29000000.0,369000000.0,-18000000.0,-124200000.0
Change To Netincome,182000000.0,-122000000.0,271000000.0,139300000.0
Capital Expenditures,-791000000.0,-636000000.0,-584000000.0,-570700000.0

In [21]:
fs.T

,Research Development,Effect Of Accounting Charges,Income Before Tax,Minority Interest,Net Income,Selling General Administrative,Gross Profit,Ebit,Operating Income,Other Operating Expenses,...,Effect Of Exchange Rate,Total Cash From Operating Activities,Depreciation,Other Cashflows From Investing Activities,Dividends Paid,Change To Inventory,Change To Account Receivables,Other Cashflows From Financing Activities,Change To Netincome,Capital Expenditures
,,,,,,,,,,,,,,,,,,,,,
2020-12-31,1348000000.0,None,4495000000.0,11000000.0,3646000000.0,6880000000.0,12932000000.0,4704000000.0,4704000000.0,None,...,148000000.0,6208000000.0,1775000000.0,24000000.0,-615000000.0,-123000000.0,-264000000.0,-29000000.0,182000000.0,-791000000.0
2019-12-31,1126000000.0,None,3305000000.0,11000000.0,3008000000.0,5577000000.0,9984000000.0,3281000000.0,3281000000.0,None,...,45000000.0,3952000000.0,1189000000.0,-43000000.0,-527000000.0,-22000000.0,-157000000.0,369000000.0,-122000000.0,-636000000.0
2018-12-31,1059000000.0,None,2962000000.0,12300000.0,2651000000.0,5356000000.0,9505000000.0,3090000000.0,3090000000.0,None,...,-118000000.0,4022000000.0,1178000000.0,-74000000.0,-433000000.0,-134000000.0,-55000000.0,-18000000.0,271000000.0,-584000000.0
2017-12-31,956400000.0,None,2543200000.0,9600000.0,2492100000.0,5011900000.0,8571300000.0,2603000000.0,2603000000.0,None,...,130700000.0,3477800000.0,1116900000.0,-57300000.0,-378300000.0,3100000.0,-142500000.0,-124200000.0,139300000.0,-570700000.0

### Download Fundamentals for Multiple Tickers Using yfinance

In [22]:
tickers = ['FB','AMZN','NFLX','GOOG']
tickers

['FB', 'AMZN', 'NFLX', 'GOOG']

In [23]:
tickers = [yf.Ticker(ticker) for ticker in tickers]
tickers

[yfinance.Ticker object <FB>,
 yfinance.Ticker object <AMZN>,
 yfinance.Ticker object <NFLX>,
 yfinance.Ticker object <GOOG>]

In [27]:
dfs = [] # list for each ticker's dataframe
for ticker in tickers:
    # get each financial statement
    pnl = ticker.financials
    bs = ticker.balancesheet
    cf = ticker.cashflow
    
    # concatenate into one dataframe
    fs = pd.concat([pnl, bs, cf])
    
    # make dataframe format nicer
    data = fs.T # Swap dates and columns
    data = data.reset_index() # reset index (date) into a column
    data.columns = ['Date', *data.columns[1:]] # Rename old index from '' to Date
    data['Ticker'] = ticker.ticker # Add ticker to dataframe
    dfs.append(data)
data

,Date,Research Development,Effect Of Accounting Charges,Income Before Tax,Minority Interest,Net Income,Selling General Administrative,Gross Profit,Ebit,Operating Income,...,Repurchase Of Stock,Effect Of Exchange Rate,Total Cash From Operating Activities,Depreciation,Other Cashflows From Investing Activities,Change To Account Receivables,Other Cashflows From Financing Activities,Change To Netincome,Capital Expenditures,Ticker
0,2020-12-31,27573000000.0,None,48082000000.0,None,40269000000.0,28998000000.0,97795000000.0,41224000000.0,41224000000.0,...,-31149000000.0,24000000.0,65124000000.0,13679000000.0,68000000.0,-6524000000.0,-2920000000.0,9349000000.0,-22281000000.0,GOOG
1,2019-12-31,26018000000.0,None,39625000000.0,None,34343000000.0,27461000000.0,89961000000.0,36482000000.0,36482000000.0,...,-18396000000.0,-23000000.0,54520000000.0,11651000000.0,589000000.0,-4340000000.0,-4545000000.0,7707000000.0,-23548000000.0,GOOG
2,2018-12-31,21419000000.0,None,34913000000.0,None,30736000000.0,23256000000.0,77270000000.0,32595000000.0,32595000000.0,...,-9075000000.0,-302000000.0,47971000000.0,9029000000.0,98000000.0,-2169000000.0,-4043000000.0,3298000000.0,-25139000000.0,GOOG
3,2017-12-31,16625000000.0,None,27193000000.0,None,12662000000.0,19733000000.0,65272000000.0,28914000000.0,28914000000.0,...,-4846000000.0,405000000.0,37091000000.0,6899000000.0,1419000000.0,-3768000000.0,-3366000000.0,8284000000.0,-13184000000.0,GOOG

In [28]:
data.iloc[:,:3]

        Date Research Development Effect Of Accounting Charges
0 2020-12-31        27573000000.0                         None
1 2019-12-31        26018000000.0                         None
2 2018-12-31        21419000000.0                         None
3 2017-12-31        16625000000.0                         None

In [29]:
parser = pd.io.parsers.base_parser.ParserBase({'usecols': None})

for df in dfs:
     df.columns = parser._maybe_dedup_names(df.columns)
df = pd.concat(dfs, ignore_index=True)
df = df.set_index(['Ticker','Date'])
df

                  Research Development Effect Of Accounting Charges  \
Ticker Date
FB     2020-12-31        18447000000.0                         None
       2019-12-31        13600000000.0                         None
       2018-12-31        10273000000.0                         None
       2017-12-31         7754000000.0                         None
AMZN   2020-12-31        42740000000.0                         None
       2019-12-31        35931000000.0                         None
       2018-12-31        28837000000.0                         None
       2017-12-31        22620000000.0                         None
NFLX   2020-12-31         1829600000.0                         None
       2019-12-31         1545149000.0                         None
       2018-12-31         1221814000.0                         None
       2017-12-31          953710000.0                         None
GOOG   2020-12-31        27573000000.0                         None
       2019-12-31        26018000000.0                         None
       2018-12-31        21419000000.0                         None
       2017-12-31        16625000000.0                         None

                  Income Before Tax Minority Interest     Net Income  \
Ticker Date
FB     2020-12-31     33180000000.0              None  29146000000.0
       2019-12-31     24812000000.0              None  18485000000.0
       2018-12-31     25361000000.0              None  22112000000.0
       2017-12-31     20594000000.0              None  15934000000.0
AMZN   2020-12-31     24194000000.0              None  21331000000.0
       2019-12-31     13962000000.0              None  11588000000.0
       2018-12-31     11270000000.0              None  10073000000.0
       2017-12-31      3802000000.0              None   3033000000.0
NFLX   2020-12-31      3199349000.0              None   2761395000.0
       2019-12-31      2062231000.0              None   1866916000.0
       2018-12-31      1226458000.0              None   1211242000.0
       2017-12-31       485321000.0              None    558929000.0
GOOG   2020-12-31     48082000000.0              None  40269000000.0
       2019-12-31     39625000000.0              None  34343000000.0
       2018-12-31     34913000000.0              None  30736000000.0
       2017-12-31     27193000000.0              None  12662000000.0

                  Selling General Administrative    Gross Profit  \
Ticker Date
FB     2020-12-31                  18155000000.0   69273000000.0
       2019-12-31                  15341000000.0   57927000000.0
       2018-12-31                  11297000000.0   46483000000.0
       2017-12-31                   7242000000.0   35199000000.0
AMZN   2020-12-31                  87193000000.0  152757000000.0
       2019-12-31                  64313000000.0  114986000000.0
       2018-12-31                  52177000000.0   93731000000.0
       2017-12-31                  38992000000.0   65932000000.0
NFLX   2020-12-31                   3304848000.0    9719737000.0
       2019-12-31                   3566831000.0    7716234000.0
       2018-12-31                   2999763000.0    5826803000.0
       2017-12-31                   1867324000.0    3659713000.0
GOOG   2020-12-31                  28998000000.0   97795000000.0
       2019-12-31                  27461000000.0   89961000000.0
       2018-12-31                  23256000000.0   77270000000.0
       2017-12-31                  19733000000.0   65272000000.0

                            Ebit Operating Income Other Operating Expenses  \
Ticker Date
FB     2020-12-31  32671000000.0    32671000000.0                     None
       2019-12-31  28986000000.0    28986000000.0                     None
       2018-12-31  24913000000.0    24913000000.0                     None
       2017-12-31  20203000000.0    20203000000.0                     None
AMZN   2020-12-31  22899000000.0    22899000000.0              -75000000.0
       2019-12-31  14404000000.0    14404000000.0              338000000.0
       2018-12-31  12421000000.0    12421000000.0              296000000.0
       2017-12-31   4106000000.0     4106000000.0              214000000.0
NFLX   2020-12-31   4585289000.0     4585289000.0                     None
       2019-12-31   2604254000.0     2604254000.0                     None
       2018-12-31   1605226000.0     1605226000.0                     None
       2017-12-31    838679000.0      838679000.0                     None
GOOG   2020-12-31  41224000000.0    41224000000.0                     None
       2019-12-31  36482000000.0    36482000000.0                     None
       2018-12-31  32595000000.0    32595000000.0                     None
       2017-12-31  28914000000.0    28914000000.0                     None

                   ... Change To Account Receivables  \
Ticker Date        ...
FB     2020-12-31  ...                 -1512000000.0
       2019-12-31  ...                 -1961000000.0
       2018-12-31  ...                 -1892000000.0
       2017-12-31  ...                 -1609000000.0
AMZN   2020-12-31  ...                 -8169000000.0
       2019-12-31  ...                 -7681000000.0
       2018-12-31  ...                 -4615000000.0
       2017-12-31  ...                 -4780000000.0
NFLX   2020-12-31  ...                           NaN
       2019-12-31  ...                           NaN
       2018-12-31  ...                           NaN
       2017-12-31  ...                           NaN
GOOG   2020-12-31  ...                 -6524000000.0
       2019-12-31  ...                 -4340000000.0
       2018-12-31  ...                 -2169000000.0
       2017-12-31  ...                 -3768000000.0

                  Other Cashflows From Financing Activities  \
Ticker Date
FB     2020-12-31                               124000000.0
       2019-12-31                                15000000.0
       2018-12-31                                15000000.0
       2017-12-31                               -13000000.0
AMZN   2020-12-31                                       NaN
       2019-12-31                                       NaN
       2018-12-31                                       NaN
       2017-12-31                                       NaN
NFLX   2020-12-31                                -7559000.0
       2019-12-31                               -36134000.0
       2018-12-31                               -37827000.0
       2017-12-31                               -31898000.0
GOOG   2020-12-31                             -2920000000.0
       2019-12-31                             -4545000000.0
       2018-12-31                             -4043000000.0
       2017-12-31                             -3366000000.0

                  Change To Netincome Capital Expenditures  \
Ticker Date
FB     2020-12-31        5462000000.0       -15115000000.0
       2019-12-31        4838000000.0       -15102000000.0
       2018-12-31        4374000000.0       -13915000000.0
       2017-12-31        3370000000.0        -6733000000.0
AMZN   2020-12-31        6001000000.0       -40140000000.0
       2019-12-31        7575000000.0       -16861000000.0
       2018-12-31        6352000000.0       -13427000000.0
       2017-12-31        4096000000.0       -11955000000.0
NFLX   2020-12-31      -11225067000.0         -497923000.0
       2019-12-31      -14117107000.0         -253035000.0
       2018-12-31      -11800733000.0         -173946000.0
       2017-12-31       -8673582000.0         -173302000.0
GOOG   2020-12-31        9349000000.0       -22281000000.0
       2019-12-31        7707000000.0       -23548000000.0
       2018-12-31        3298000000.0       -25139000000.0
       2017-12-31        8284000000.0       -13184000000.0

                  Short Long Term Debt Long Term Debt      Inventory  \
Ticker Date
FB     2020-12-31                  NaN            NaN            NaN
       2019-12-31                  NaN            NaN            NaN
       2018-12-31                  NaN            NaN            NaN
       2017-12-31                  NaN            NaN            NaN
AMZN   2020-12-31         1155000000.0  31816000000.0  23795000000.0
       2019-12-31         1305000000.0  23414000000.0  20497000000.0
       2018-12-31         1371000000.0  23495000000.0  17174000000.0
       2017-12-31          100000000.0  24743000000.0  16047000000.0
NFLX   2020-12-31          499878000.0  15809095000.0            NaN
       2019-12-31                  NaN  14759260000.0            NaN
       2018-12-31                  NaN  10360058000.0            NaN
       2017-12-31                  NaN   6499432000.0            NaN
GOOG   2020-12-31          999000000.0  12832000000.0    728000000.0
       2019-12-31                  NaN   3958000000.0    999000000.0
       2018-12-31                  NaN   3950000000.0   1107000000.0
       2017-12-31                  NaN   3943000000.0    749000000.0

                  Change To Inventory Deferred Long Term Asset Charges  \
Ticker Date
FB     2020-12-31                 NaN                              NaN
       2019-12-31                 NaN                              NaN
       2018-12-31                 NaN                              NaN
       2017-12-31                 NaN                              NaN
AMZN   2020-12-31       -2849000000.0                              NaN
       2019-12-31       -3278000000.0                              NaN
       2018-12-31       -1314000000.0                              NaN
       2017-12-31       -3583000000.0                              NaN
NFLX   2020-12-31                 NaN                      589091000.0
       2019-12-31                 NaN                      658206000.0
       2018-12-31                 NaN                      564425000.0
       2017-12-31                 NaN                      478266000.0
GOOG   2020-12-31                 NaN                     1084000000.0
       2019-12-31                 NaN                      721000000.0
       2018-12-31                 NaN                      737000000.0
       2017-12-31                 NaN                      680000000.0

                  Issuance Of Stock
Ticker Date
FB     2020-12-31               NaN
       2019-12-31               NaN
       2018-12-31               NaN
       2017-12-31               NaN
AMZN   2020-12-31               NaN
       2019-12-31               NaN
       2018-12-31               NaN
       2017-12-31               NaN
NFLX   2020-12-31       235406000.0
       2019-12-31        72490000.0
       2018-12-31       124502000.0
       2017-12-31        88378000.0
GOOG   2020-12-31               NaN
       2019-12-31               NaN
       2018-12-31               NaN
       2017-12-31               NaN

[16 rows x 68 columns]

## Hows to Get Options Data Using yfinance

Options give traders the right but not the obligation to buy or sell underlying assets at a specific price at a predetermined date. Options Trading has matured over the past century and has seen landmark events. Here is a chronicle of the history of options trading and the major events that have led to its evolution.

To download options data, you'll need to use the `Ticker.options` and `Ticker.option_chain` methods.

In [31]:
aapl = yf.Ticker('aapl')
aapl

yfinance.Ticker object <AAPL>

In [32]:
options = aapl.option_chain()

In [33]:
calls = options.calls
calls

,contractSymbol,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,impliedVolatility,inTheMoney,contractSize,currency
0,AAPL220114C00105000,2022-01-12 20:54:40+00:00,105.0,70.40,69.85,71.10,1.150001,1.660652,1.0,6,3.169924,True,REGULAR,USD
1,AAPL220114C00110000,2022-01-11 18:48:02+00:00,110.0,64.65,64.60,66.10,0.000000,0.000000,3.0,13,2.920901,True,REGULAR,USD
2,AAPL220114C00115000,2022-01-11 20:44:10+00:00,115.0,59.95,60.35,60.55,0.000000,0.000000,NaN,3,1.703126,True,REGULAR,USD
3,AAPL220114C00120000,2022-01-10 17:04:36+00:00,120.0,48.65,55.35,55.85,0.000000,0.000000,2.0,44,1.773439,True,REGULAR,USD
4,AAPL220114C00125000,2022-01-10 20:12:22+00:00,125.0,45.37,50.35,50.90,0.000000,0.000000,5.0,88,1.664064,True,REGULAR,USD
5,AAPL220114C00130000,2022-01-11 19:44:31+00:00,130.0,46.00,45.35,45.90,1.349999,3.023513,1.0,113,1.492190,True,REGULAR,USD
6,AAPL220114C00135000,2022-01-10 16:06:25+00:00,135.0,38.50,40.35,40.90,0.000000,0.000000,5.0,7,1.328128,True,REGULAR,USD
7,AAPL220114C00140000,2022-01-12 18:30:21+00:00,140.0,35.55,35.35,35.90,1.389999,4.069085,31.0,843,1.164067,True,REGULAR,USD
8,AAPL220114C00141000,2022-01-07 16:23:06+00:00,141.0,30.30,34.35,34.90,0.000000,0.000000,5.0,4,1.132817,True,REGULAR,USD
9,AAPL220114C00142000,2022-01-12 16:07:17+00:00,142.0,32.90,33.35,33.90,5.100002,18.345333,3.0,5,1.101567,True,REGULAR,USD
10,AAPL220114C00143000,2022-01-10 18:23:53+00:00,143.0,27.65,32.35,32.90,0.000000,0.000000,4.0,190,1.068364,True,REGULAR,USD
11,AAPL220114C00144000,2022-01-11 14:31:12+00:00,144.0,27.90,31.30,31.90,0.000000,0.000000,5.0,32,0.992188,True,REGULAR,USD
12,AAPL220114C00145000,2022-01-11 19:45:09+00:00,145.0,29.83,30.35,30.90,0.000000,0.000000,6.0,594,1.003911,True,REGULAR,USD
13,AAPL220114C00146000,2022-01-11 16:17:56+00:00,146.0,27.80,29.30,29.90,0.000000,0.000000,14.0,50,0.933594,True,REGULAR,USD
14,AAPL220114C00147000,2022-01-11 20:37:07+00:00,147.0,28.12,28.30,28.90,0.000000,0.000000,21.0,76,0.902345,True,REGULAR,USD
15,AAPL220114C00148000,2022-01-12 14:31:30+00:00,148.0,28.45,27.35,27.90,2.700001,10.485439,2.0,240,0.910157,True,REGULAR,USD
16,AAPL220114C00149000,2022-01-11 15:41:02+00:00,149.0,27.61,26.30,26.90,5.110001,22.711113,1.0,34,0.841798,True,REGULAR,USD
17,AAPL220114C00150000,2022-01-12 20:57:24+00:00,150.0,25.33,25.35,25.90,0.180000,0.715707,44.0,615,0.849611,True,REGULAR,USD
18,AAPL220114C00152500,2022-01-12 19:17:36+00:00,152.5,23.10,22.85,23.40,0.700001,3.125003,24.0,199,0.773440,True,REGULAR,USD
19,AAPL220114C00155000,2022-01-12 20:44:27+00:00,155.0,20.65,20.35,20.70,0.850000,4.292932,63.0,783,0.767580,True,REGULAR,USD
20,AAPL220114C00157500,2022-01-12 20:57:04+00:00,157.5,17.90,17.85,18.20,0.699999,4.069760,529.0,1709,0.685550,True,REGULAR,USD
21,AAPL220114C00160000,2022-01-12 20:58:57+00:00,160.0,15.50,15.40,15.90,0.800000,5.442178,499.0,5588,0.564457,True,REGULAR,USD
22,AAPL220114C00162500,2022-01-12 20:51:53+00:00,162.5,12.95,12.90,13.45,0.450000,3.599998,251.0,1454,0.503911,True,REGULAR,USD
23,AAPL220114C00165000,2022-01-12 20:44:14+00:00,165.0,10.25,10.40,10.95,0.150000,1.485145,727.0,2472,0.543950,True,REGULAR,USD
24,AAPL220114C00167500,2022-01-12 20:55:19+00:00,167.5,8.15,7.95,8.45,0.559999,7.378122,1813.0,3331,0.444830,True,REGULAR,USD
25,AAPL220114C00170000,2022-01-12 20:59:59+00:00,170.0,5.64,5.55,5.90,0.180000,3.296700,8726.0,22545,0.328132,True,REGULAR,USD
26,AAPL220114C00172500,2022-01-12 20:59:59+00:00,172.5,3.50,3.30,3.60,0.170000,5.105108,24387.0,23924,0.264412,True,REGULAR,USD
27,AAPL220114C00175000,2022-01-12 20:59:58+00:00,175.0,1.65,1.56,1.67,-0.020000,-1.197604,78697.0,40383,0.219246,True,REGULAR,USD
28,AAPL220114C00177500,2022-01-12 20:59:58+00:00,177.5,0.54,0.50,0.55,-0.130000,-19.402985,233135.0,31059,0.204598,False,REGULAR,USD
29,AAPL220114C00180000,2022-01-12 21:00:00+00:00,180.0,0.13,0.12,0.14,-0.080000,-38.095238,92346.0,49913,0.207039,False,REGULAR,USD
30,AAPL220114C00182500,2022-01-12 20:59:55+00:00,182.5,0.04,0.03,0.04,-0.030000,-42.857143,25306.0,22985,0.224617,False,REGULAR,USD
31,AAPL220114C00185000,2022-01-12 20:59:47+00:00,185.0,0.01,0.00,0.01,-0.010000,-50.000000,19832.0,25932,0.242195,False,REGULAR,USD
32,AAPL220114C00187500,2022-01-12 20:45:37+00:00,187.5,0.01,0.00,0.01,-0.010000,-50.000000,2826.0,9279,0.289070,False,REGULAR,USD
33,AAPL220114C00190000,2022-01-12 20:52:55+00:00,190.0,0.01,0.00,0.01,0.000000,0.000000,1605.0,12591,0.343757,False,REGULAR,USD
34,AAPL220114C00192500,2022-01-12 20:40:37+00:00,192.5,0.01,0.00,0.01,0.000000,0.000000,418.0,14500,0.390631,False,REGULAR,USD
35,AAPL220114C00195000,2022-01-12 20:49:08+00:00,195.0,0.01,0.00,0.01,0.000000,0.000000,87.0,6207,0.437506,False,REGULAR,USD
36,AAPL220114C00197500,2022-01-12 15:10:23+00:00,197.5,0.01,0.00,0.01,0.000000,0.000000,2.0,2157,0.484380,False,REGULAR,USD
37,AAPL220114C00200000,2022-01-12 16:29:47+00:00,200.0,0.01,0.00,0.01,0.000000,0.000000,211.0,11998,0.500005,False,REGULAR,USD
38,AAPL220114C00202500,2022-01-12 15:42:05+00:00,202.5,0.01,0.00,0.01,0.000000,0.000000,2.0,1555,0.546880,False,REGULAR,USD
39,AAPL220114C00205000,2022-01-12 16:49:48+00:00,205.0,0.01,0.00,0.01,0.000000,0.000000,3.0,4568,0.593754,False,REGULAR,USD
40,AAPL220114C00210000,2022-01-11 19:51:20+00:00,210.0,0.01,0.00,0.01,0.000000,0.000000,1.0,3209,0.656253,False,REGULAR,USD
41,AAPL220114C00215000,2022-01-10 17:30:58+00:00,215.0,0.01,0.00,0.01,0.000000,0.000000,20.0,2063,0.750003,False,REGULAR,USD
42,AAPL220114C00220000,2022-01-10 14:30:07+00:00,220.0,0.01,0.00,0.01,0.000000,0.000000,22.0,2168,0.812502,False,REGULAR,USD
43,AAPL220114C00225000,2022-01-05 20:48:52+00:00,225.0,0.01,0.00,0.01,0.000000,0.000000,2.0,1273,0.906251,False,REGULAR,USD
44,AAPL220114C00230000,2022-01-06 20:55:13+00:00,230.0,0.01,0.00,0.01,0.000000,0.000000,2.0,1991,0.968750,False,REGULAR,USD
45,AAPL220114C00235000,2022-01-04 19:30:50+00:00,235.0,0.01,0.00,0.01,0.000000,0.000000,38.0,770,1.031255,False,REGULAR,USD
46,AAPL220114C00240000,2022-01-12 14:30:00+00:00,240.0,0.01,0.00,0.01,0.000000,0.000000,1.0,1419,1.093755,False,REGULAR,USD
47,AAPL220114C00245000,2022-01-07 15:49:01+00:00,245.0,0.01,0.00,0.01,0.000000,0.000000,2.0,1296,1.156254,False,REGULAR,USD
48,AAPL220114C00250000,2022-01-12 15:56:53+00:00,250.0,0.01,0.00,0.01,0.000000,0.000000,3.0,9,1.250004,False,REGULAR,USD

In [34]:
type(options)

yfinance.ticker.Options

In [35]:
puts = options.puts
puts

,contractSymbol,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,impliedVolatility,inTheMoney,contractSize,currency
0,AAPL220114P00105000,2022-01-10 15:57:00+00:00,105.0,0.01,0.00,0.01,0.000000,0.000000,4.0,871.0,1.812501,False,REGULAR,USD
1,AAPL220114P00110000,2022-01-03 20:33:37+00:00,110.0,0.01,0.00,0.01,0.000000,0.000000,8.0,56.0,1.625002,False,REGULAR,USD
2,AAPL220114P00115000,2022-01-07 17:40:08+00:00,115.0,0.01,0.00,0.01,0.000000,0.000000,2.0,2481.0,1.500002,False,REGULAR,USD
3,AAPL220114P00120000,2022-01-10 16:04:20+00:00,120.0,0.01,0.00,0.01,0.000000,0.000000,1.0,3411.0,1.375003,False,REGULAR,USD
4,AAPL220114P00125000,2022-01-10 20:42:10+00:00,125.0,0.01,0.00,0.01,0.000000,0.000000,69.0,3194.0,1.218754,False,REGULAR,USD
5,AAPL220114P00130000,2022-01-10 20:25:01+00:00,130.0,0.01,0.00,0.01,0.000000,0.000000,362.0,3399.0,1.093755,False,REGULAR,USD
6,AAPL220114P00135000,2022-01-11 18:25:27+00:00,135.0,0.01,0.00,0.01,0.000000,0.000000,192.0,2239.0,0.968750,False,REGULAR,USD
7,AAPL220114P00140000,2022-01-12 19:47:03+00:00,140.0,0.01,0.00,0.02,0.000000,0.000000,21.0,2589.0,0.890626,False,REGULAR,USD
8,AAPL220114P00141000,2022-01-12 20:59:38+00:00,141.0,0.01,0.00,0.01,0.000000,0.000000,210.0,1619.0,0.812502,False,REGULAR,USD
9,AAPL220114P00142000,2022-01-12 20:59:41+00:00,142.0,0.01,0.00,0.01,0.000000,0.000000,517.0,1518.0,0.781252,False,REGULAR,USD
10,AAPL220114P00143000,2022-01-12 20:56:51+00:00,143.0,0.02,0.00,0.02,0.010000,100.000000,223.0,1581.0,0.812502,False,REGULAR,USD
11,AAPL220114P00144000,2022-01-12 18:51:19+00:00,144.0,0.01,0.00,0.02,-0.010000,-50.000000,78.0,2272.0,0.796877,False,REGULAR,USD
12,AAPL220114P00145000,2022-01-12 20:46:04+00:00,145.0,0.01,0.01,0.04,0.000000,0.000000,300.0,3826.0,0.843752,False,REGULAR,USD
13,AAPL220114P00146000,2022-01-12 20:46:02+00:00,146.0,0.01,0.01,0.02,-0.010000,-50.000000,141.0,3070.0,0.773440,False,REGULAR,USD
14,AAPL220114P00147000,2022-01-12 19:31:17+00:00,147.0,0.01,0.00,0.04,-0.010000,-50.000000,1.0,1233.0,0.773440,False,REGULAR,USD
15,AAPL220114P00148000,2022-01-12 15:22:57+00:00,148.0,0.01,0.01,0.02,-0.010000,-50.000000,183.0,2691.0,0.718753,False,REGULAR,USD
16,AAPL220114P00149000,2022-01-12 19:53:38+00:00,149.0,0.02,0.01,0.02,0.000000,0.000000,380.0,3349.0,0.695316,False,REGULAR,USD
17,AAPL220114P00150000,2022-01-12 20:59:39+00:00,150.0,0.02,0.01,0.02,0.000000,0.000000,2308.0,5605.0,0.671878,False,REGULAR,USD
18,AAPL220114P00152500,2022-01-12 20:54:30+00:00,152.5,0.02,0.02,0.03,-0.010000,-33.333336,1891.0,2909.0,0.640629,False,REGULAR,USD
19,AAPL220114P00155000,2022-01-12 20:59:21+00:00,155.0,0.03,0.02,0.04,-0.010000,-25.000000,21509.0,11087.0,0.589848,False,REGULAR,USD
20,AAPL220114P00157500,2022-01-12 20:58:39+00:00,157.5,0.04,0.02,0.04,-0.010000,-20.000004,1506.0,4894.0,0.523442,False,REGULAR,USD
21,AAPL220114P00160000,2022-01-12 20:59:35+00:00,160.0,0.05,0.04,0.05,-0.010000,-16.666664,3517.0,13459.0,0.490239,False,REGULAR,USD
22,AAPL220114P00162500,2022-01-12 20:58:56+00:00,162.5,0.05,0.05,0.06,-0.040000,-44.444447,3730.0,9698.0,0.431646,False,REGULAR,USD
23,AAPL220114P00165000,2022-01-12 21:00:00+00:00,165.0,0.06,0.06,0.07,-0.070000,-53.846150,9175.0,15412.0,0.367194,False,REGULAR,USD
24,AAPL220114P00167500,2022-01-12 20:59:58+00:00,167.5,0.09,0.07,0.10,-0.140000,-60.869564,8546.0,12259.0,0.312507,False,REGULAR,USD
25,AAPL220114P00170000,2022-01-12 20:59:57+00:00,170.0,0.20,0.16,0.20,-0.230000,-53.488373,18292.0,22395.0,0.273933,False,REGULAR,USD
26,AAPL220114P00172500,2022-01-12 20:59:59+00:00,172.5,0.39,0.40,0.49,-0.460000,-54.117650,21572.0,14998.0,0.247566,False,REGULAR,USD
27,AAPL220114P00175000,2022-01-12 20:59:58+00:00,175.0,1.19,1.08,1.19,-0.470000,-28.313250,77724.0,11355.0,0.227059,False,REGULAR,USD
28,AAPL220114P00177500,2022-01-12 20:59:57+00:00,177.5,2.57,2.39,2.66,-0.610000,-19.182394,16105.0,14461.0,0.230232,True,REGULAR,USD
29,AAPL220114P00180000,2022-01-12 20:58:00+00:00,180.0,4.75,4.25,4.80,-0.400000,-7.766992,1063.0,10934.0,0.266121,True,REGULAR,USD
30,AAPL220114P00182500,2022-01-12 20:57:43+00:00,182.5,7.19,6.65,7.20,-0.360000,-4.768214,306.0,2291.0,0.325202,True,REGULAR,USD
31,AAPL220114P00185000,2022-01-12 20:13:32+00:00,185.0,9.50,9.15,9.70,-0.400000,-4.040400,276.0,3208.0,0.406256,True,REGULAR,USD
32,AAPL220114P00187500,2022-01-12 16:30:55+00:00,187.5,11.62,11.65,12.20,-1.480001,-11.297713,22.0,120.0,0.483404,True,REGULAR,USD
33,AAPL220114P00190000,2022-01-12 20:44:04+00:00,190.0,14.55,14.15,14.70,-0.450000,-2.999999,24.0,328.0,0.556645,True,REGULAR,USD
34,AAPL220114P00192500,2022-01-12 14:47:21+00:00,192.5,17.04,16.65,17.20,-0.359999,-2.068958,1.0,35.0,0.626957,True,REGULAR,USD
35,AAPL220114P00195000,2022-01-12 14:38:13+00:00,195.0,18.48,19.15,19.70,-1.860001,-9.144546,2.0,29.0,0.695316,True,REGULAR,USD
36,AAPL220114P00197500,2022-01-12 17:25:20+00:00,197.5,21.65,21.60,22.15,-4.470001,-17.113327,25.0,11.0,0.726565,True,REGULAR,USD
37,AAPL220114P00200000,2022-01-12 20:25:07+00:00,200.0,24.59,24.10,24.70,-0.510000,-2.031874,2.0,65.0,0.825197,True,REGULAR,USD
38,AAPL220114P00202500,2022-01-07 16:09:03+00:00,202.5,31.00,26.65,27.20,0.000000,0.000000,2.0,1.0,0.887696,True,REGULAR,USD
39,AAPL220114P00205000,2022-01-10 20:40:52+00:00,205.0,33.62,29.15,29.70,0.000000,0.000000,3.0,2.0,0.949219,True,REGULAR,USD
40,AAPL220114P00210000,2022-01-11 20:44:10+00:00,210.0,35.05,34.00,34.95,0.000000,0.000000,3.0,0.0,0.671878,True,REGULAR,USD
41,AAPL220114P00215000,2022-01-11 19:09:47+00:00,215.0,41.05,38.60,40.40,0.000000,0.000000,10.0,0.0,0.890626,True,REGULAR,USD
42,AAPL220114P00220000,2022-01-03 20:54:40+00:00,220.0,38.50,43.75,45.00,0.000000,0.000000,NaN,0.0,1.496096,True,REGULAR,USD
43,AAPL220114P00225000,2022-01-12 19:23:38+00:00,225.0,49.30,49.00,50.25,-3.940002,-7.400455,2.0,0.0,1.308597,True,REGULAR,USD
44,AAPL220114P00240000,2022-01-11 17:43:03+00:00,240.0,65.75,64.50,64.70,0.000000,0.000000,NaN,NaN,1.550783,True,REGULAR,USD
45,AAPL220114P00245000,2022-01-11 17:43:03+00:00,245.0,70.75,68.90,70.35,0.000000,0.000000,3.0,0.0,1.675783,True,REGULAR,USD
46,AAPL220114P00250000,2022-01-11 17:43:03+00:00,250.0,75.75,74.30,74.45,0.000000,0.000000,NaN,1.0,0.000010,True,REGULAR,USD

## How to Get Institutional Holders Using yfinance

In [36]:
aapl.institutional_holders

,Holder,Shares,Date Reported,% Out,Value
0,"Vanguard Group, Inc. (The)",1266332667,2021-09-29,0.0775,179186072380
1,Blackrock Inc.,1026223983,2021-09-29,0.0628,145210693594
2,"Berkshire Hathaway, Inc",887135554,2021-09-29,0.0543,125529680891
3,State Street Corporation,622163541,2021-09-29,0.0381,88036141051
4,"FMR, LLC",350617759,2021-09-29,0.0215,49612412898
5,"Geode Capital Management, LLC",259894947,2021-09-29,0.0159,36775135000
6,Northern Trust Corporation,195321532,2021-09-29,0.0120,27637996778
7,Price (T.Rowe) Associates Inc,188489966,2021-09-29,0.0115,26671330189
8,Norges Bank Investment Management,167580974,2020-12-30,0.0103,22236319440
9,Bank Of New York Mellon Corporation,149381117,2021-09-29,0.0091,21137428055

## Why You Shouldn’t Use Yahoo Finance for Live Trading

In [38]:
fb = yf.Ticker('fb')
meta = yf.Ticker('meta')
fb.get_cashflow()

,2020-12-31,2019-12-31,2018-12-31,2017-12-31
Investments,-1.452000e+10,-4.254000e+09,2.449000e+09,-1.325000e+10
Change To Liabilities,9.100000e+07,2.360000e+08,2.740000e+08,4.700000e+07
Total Cashflows From Investing Activities,-3.005900e+10,-1.986400e+10,-1.160300e+10,-2.011800e+10
Net Borrowings,-5.800000e+08,-7.750000e+08,5.000000e+08,5.000000e+08
Total Cash From Financing Activities,-1.029200e+10,-7.299000e+09,-1.557200e+10,-5.235000e+09
Change To Operating Activities,-1.302000e+09,8.975000e+09,9.100000e+07,3.449000e+09
Net Income,2.914600e+10,1.848500e+10,2.211200e+10,1.593400e+10
Change In Cash,-1.325000e+09,9.155000e+09,1.920000e+09,-9.050000e+08
Repurchase Of Stock,-9.836000e+09,-6.539000e+09,-1.608700e+10,-5.222000e+09
Effect Of Exchange Rate,2.790000e+08,4.000000e+06,-1.790000e+08,2.320000e+08
Total Cash From Operating Activities,3.874700e+10,3.631400e+10,2.927400e+10,2.421600e+10
Depreciation,6.862000e+09,5.741000e+09,4.315000e+09,3.025000e+09
Other Cashflows From Investing Activities,-3.600000e+07,-3.600000e+07,-3.600000e+07,-1.300000e+07
Change To Account Receivables,-1.512000e+09,-1.961000e+09,-1.892000e+09,-1.609000e+09
Other Cashflows From Financing Activities,1.240000e+08,1.500000e+07,1.500000e+07,-1.300000e+07
Change To Netincome,5.462000e+09,4.838000e+09,4.374000e+09,3.370000e+09
Capital Expenditures,-1.511500e+10,-1.510200e+10,-1.391500e+10,-6.733000e+09

In [39]:
meta.get_cashflow()

Empty DataFrame
Columns: [Open, High, Low, Close, Adj Close, Volume]
Index: []